const $ = s => document.querySelector(s);
const savedSettings = JSON.parse(localStorage.getItem('aster:settings') || '{}');
const state = {threads:[],projects:[],tasks:[],projectFilter:null,searchIds:null,active:null,busy:false,token:sessionStorage.getItem('aster:token') || '',controller:null,api:true,auth:null,settings:{model:'gemma4:12b',compact:false,accountEmail:'',displayName:'Profil principal',profileRole:'personal',allowedModels:'gemma4:12b',rulePreset:'balanced',profileRules:'',allowedSkills:'writing,summary',capacityPreset:'essential',parallelRequests:1,capacityOverride:false,networkMode:'direct',proxyUrl:'',...savedSettings}};
const headers = json => ({...(state.token ? {authorization:`Bearer ${state.token}`} : {}),...(json ? {'content-type':'application/json'} : {})});
const escapeHtml = s => {const d=document.createElement('div');d.textContent=s ?? '';return d.innerHTML};
const current = () => state.threads.find(t=>t.id===state.active);
const normalize = t => ({id:t.id || crypto.randomUUID(),title:t.title || 'Nouvelle conversation',projectId:t.projectId||null,created:t.created || t.createdAt || Date.now(),messages:Array.isArray(t.messages)?t.messages:[]});

function localSave(){} // Les conversations ne sont jamais copiées dans le stockage partagé du navigateur.
async function request(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{...headers(options.body),...options.headers}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error || `Erreur ${r.status}`);return r.status===204?null:r.json();}
async function hydrate(t){if(!state.api||t.loaded)return t;try{const full=await request(`/api/conversations/${encodeURIComponent(t.id)}`);Object.assign(t,normalize(full),{loaded:true});}catch{state.api=false;}return t;}
async function loadThreads(){try{const [data,projectData,taskData]=await Promise.all([request('/api/conversations'),request('/api/projects'),request('/api/tasks')]);state.threads=(Array.isArray(data)?data:data.conversations||[]).map(normalize);state.projects=projectData.projects||[];state.tasks=taskData.tasks||[];state.api=true;}catch{state.api=false;state.threads=[];state.projects=[];state.tasks=[];}if(!state.threads.length)await newThread();else{state.active=state.threads[0].id;await hydrate(state.threads[0]);}renderAll();}
async function saveThread(t){localSave();if(!state.api)return;try{await request(`/api/conversations/${encodeURIComponent(t.id)}`,{method:'PUT',body:JSON.stringify(t)});}catch{state.api=false;}}
async function newThread(){let t=normalize({projectId:state.projectFilter});if(state.api){try{const made=await request('/api/conversations',{method:'POST',body:JSON.stringify(t)});t=normalize(made?.conversation||made||t);}catch{state.api=false;}}state.threads.unshift(t);state.active=t.id;localSave();renderAll();$('#prompt').focus();closeSidebar();}
function renderThreads(){const host=$('#threads');host.innerHTML='';const visible=state.threads.filter(t=>(!state.projectFilter||t.projectId===state.projectFilter)&&(!state.searchIds||state.searchIds.has(t.id)));for(const t of visible){const row=document.createElement('div');row.className=`thread-row ${t.id===state.active?'active':''}`;row.innerHTML=`<button class="thread" data-id="${escapeHtml(t.id)}">${escapeHtml(t.title)}</button><button class="thread-menu" aria-label="Actions pour ${escapeHtml(t.title)}">•••</button>`;row.querySelector('.thread-menu').onclick=e=>threadActions(t,e.currentTarget);host.append(row);}if(!visible.length)host.innerHTML='<p class="thread-empty">Aucune conversation ici.</p>';}
function threadActions(t,anchor){document.querySelector('.thread-popover')?.remove();const p=document.createElement('div');p.className='thread-popover';p.innerHTML='<button data-action="rename">Renommer</button><button data-action="move">Déplacer</button><button data-action="delete" class="danger">Supprimer</button>';anchor.parentElement.append(p);p.onclick=async e=>{const action=e.target.dataset.action;if(action==='rename'){const title=prompt('Nouveau nom',t.title)?.trim();if(title){t.title=title.slice(0,80);await saveThread(t);renderThreads();}}if(action==='move'){const choices=['0 · Sans projet',...state.projects.map((project,index)=>`${index+1} · ${project.name}`)].join('\n');const selected=prompt(`Déplacer vers :\n${choices}`);if(selected!==null){const index=Number(selected.split('·')[0].trim());if(Number.isInteger(index)&&index>=0&&index<=state.projects.length){t.projectId=index===0?null:state.projects[index-1].id;await saveThread(t);renderAll();}}}if(action==='delete'&&confirm(`Supprimer « ${t.title} » ?`)){if(state.api)await request(`/api/conversations/${encodeURIComponent(t.id)}`,{method:'DELETE'}).catch(()=>state.api=false);state.threads=state.threads.filter(x=>x.id!==t.id);if(state.active===t.id)state.active=state.threads[0]?.id||null;localSave();if(!state.active)await newThread();renderAll();}p.remove();};}
function renderProjects(){const host=$('#projectList');if(!host)return;host.innerHTML=`<button type="button" data-project="" class="${state.projectFilter?'':'active'}">Toutes</button>${state.projects.map(project=>`<div class="project-row"><button type="button" data-project="${project.id}" class="${state.projectFilter===project.id?'active':''}">${escapeHtml(project.name)}</button><button type="button" data-project-actions="${project.id}" aria-label="Actions pour ${escapeHtml(project.name)}">•••</button></div>`).join('')}`;host.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>{state.projectFilter=button.dataset.project||null;renderAll();});host.querySelectorAll('[data-project-actions]').forEach(button=>button.onclick=()=>projectActions(button.dataset.projectActions));}
async function projectActions(projectId){const project=state.projects.find(item=>item.id===projectId);if(!project)return;const action=prompt(`Projet « ${project.name} » : saisissez R pour renommer ou S pour supprimer.`)?.trim().toUpperCase();if(action==='R'){const name=prompt('Nouveau nom du projet',project.name)?.trim();if(!name)return;try{const data=await request(`/api/projects/${project.id}`,{method:'PATCH',body:JSON.stringify({name})});Object.assign(project,data.project);renderAll();}catch(error){alert(error.message);}}if(action==='S'&&confirm(`Supprimer le projet « ${project.name} » ? Les conversations et tâches resteront disponibles.`)){try{await request(`/api/projects/${project.id}`,{method:'DELETE'});state.projects=state.projects.filter(item=>item.id!==project.id);state.threads.forEach(thread=>{if(thread.projectId===project.id)thread.projectId=null;});state.tasks.forEach(task=>{if(task.projectId===project.id)task.projectId=null;});if(state.projectFilter===project.id)state.projectFilter=null;renderAll();}catch(error){alert(error.message);}}}
function renderTasks(){const host=$('#taskList');if(!host)return;const tasks=state.tasks.filter(task=>!state.projectFilter||task.projectId===state.projectFilter).sort((a,b)=>Number(a.done)-Number(b.done)||String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));host.innerHTML=tasks.length?tasks.map(task=>`<div class="task-row ${task.done?'done':''}"><input type="checkbox" data-task-toggle="${task.id}" ${task.done?'checked':''} aria-label="Marquer ${escapeHtml(task.title)} comme ${task.done?'à faire':'terminée'}"><span>${escapeHtml(task.title)}${task.dueDate?`<small>${escapeHtml(task.dueDate)}</small>`:''}</span><button type="button" data-task-delete="${task.id}" aria-label="Supprimer ${escapeHtml(task.title)}">×</button></div>`).join(''):'<p class="planning-empty">Aucune tâche. Ajoutez la prochaine action utile.</p>';host.querySelectorAll('[data-task-toggle]').forEach(input=>input.onchange=()=>updateTask(input.dataset.taskToggle,{done:input.checked}));host.querySelectorAll('[data-task-delete]').forEach(button=>button.onclick=()=>deleteTask(button.dataset.taskDelete));}
async function updateTask(id,patch){try{const {task}=await request(`/api/tasks/${id}`,{method:'PATCH',body:JSON.stringify(patch)});const index=state.tasks.findIndex(item=>item.id===id);if(index>=0)state.tasks[index]=task;renderTasks();}catch(error){alert(error.message);await loadThreads();}}
async function deleteTask(id){const task=state.tasks.find(item=>item.id===id);if(!task||!confirm(`Supprimer « ${task.title} » ?`))return;try{await request(`/api/tasks/${id}`,{method:'DELETE'});state.tasks=state.tasks.filter(item=>item.id!==id);renderTasks();}catch(error){alert(error.message);}}
function renderChat(){const t=current(),has=t?.messages.length;$('#empty').hidden=!!has;$('#messages').classList.toggle('visible',!!has);$('#messages').innerHTML=has?t.messages.map(m=>`<article class="message ${m.role}"><div class="avatar">${m.role==='user'?'VOUS':'✦'}</div><div class="content">${escapeHtml(m.content)}</div></article>`).join(''):'';$('#chat').scrollTop=$('#chat').scrollHeight;}
function renderAll(){renderProjects();renderTasks();renderThreads();renderChat();document.body.classList.toggle('compact',state.settings.compact);const name=state.settings.displayName||'Profil local',initial=name.trim().charAt(0).toUpperCase()||'P';$('#profileName').textContent=name;$('#profileAvatar').textContent=initial;if($('#profileAvatarLarge'))$('#profileAvatarLarge').textContent=initial;}
function setBusy(value){state.busy=value;document.body.classList.toggle('model-working',value);$('#send').hidden=value;$('#stop').hidden=!value;$('#prompt').disabled=value;}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#scrim').hidden=true;$('#menuBtn').setAttribute('aria-expanded','false');}
async function refresh(){let online=false,server=true;try{const h=await request('/api/health');online=!!h.ollama;$('#status span').textContent=online?'Moteur prêt':'Moteur à configurer';if(!online){$('#offlineTitle').textContent='Le moteur local attend Ollama';$('#offlineCopy').textContent='Installez ou lancez Ollama, puis ajoutez Gemma. Aster reste disponible pour gérer vos conversations.';}try{const data=await request('/api/models');const models=data.models||[];if(models.length)$('#model').innerHTML=models.map(m=>`<option>${escapeHtml(m.name)}</option>`).join('');}catch{}}catch{server=false;$('#status span').textContent='Service Aster indisponible';$('#offlineTitle').textContent='Le service local ne répond plus';$('#offlineCopy').textContent='Vos données restent sur cet appareil. Relancez Aster puis testez à nouveau la connexion.';}$('#status').className=`status ${server?(online?'ready':'setup'):'disconnected'}`;$('#offlineHelp').hidden=online;const wanted=state.settings.model;if(!Array.from($('#model').options).some(o=>o.value===wanted))$('#model').add(new Option(wanted,wanted));$('#model').value=wanted;}
async function send(text){if(!text.trim()||state.busy)return;if(!current())await newThread();const t=current(),clean=text.trim();t.messages.push({role:'user',content:clean});if(t.messages.length===1)t.title=clean.slice(0,42);t.messages.push({role:'assistant',content:''});state.controller=new AbortController();setBusy(true);await saveThread(t);renderAll();try{const r=await fetch('/api/chat',{method:'POST',headers:headers(true),signal:state.controller.signal,body:JSON.stringify({model:$('#model').value,messages:t.messages.slice(0,-1)})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Erreur du modèle');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(line.trim()){const part=JSON.parse(line);t.messages.at(-1).content+=part.message?.content||'';}}renderChat();}if(!t.messages.at(-1).content)t.messages.at(-1).content='Aucune réponse reçue.';}catch(e){if(e.name==='AbortError'){t.messages.at(-1).content ||= 'Génération arrêtée.';}else t.messages.at(-1).content=`Impossible de répondre : ${e.message}\n\nVérifiez qu’Ollama est lancé et que le modèle est installé.`;}finally{state.controller=null;setBusy(false);await saveThread(t);renderAll();}}
async function exportData(){if(state.auth?.user?.role!=='admin')return alert('Seul l’administrateur local peut créer une sauvegarde complète.');const passphrase=prompt('Phrase secrète de sauvegarde (12 caractères minimum). Elle sera indispensable pour restaurer les données.');if(passphrase===null)return;try{const {backup}=await request('/api/admin/backup',{method:'POST',body:JSON.stringify({passphrase})});const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aster-backup-${new Date().toISOString().slice(0,10)}.aster.json`;a.click();URL.revokeObjectURL(a.href);}catch(e){alert(`Sauvegarde impossible : ${e.message}`);}}
async function importData(file){if(state.auth?.user?.role!=='admin')return alert('Seul l’administrateur local peut restaurer une sauvegarde.');const passphrase=prompt('Phrase secrète de cette sauvegarde.');if(passphrase===null)return;const confirmation=prompt('Cette opération remplacera tous les comptes, profils et conversations. Saisissez RESTAURER pour continuer.');if(confirmation!=='RESTAURER')return;try{const backup=JSON.parse(await file.text());const result=await request('/api/admin/restore',{method:'POST',body:JSON.stringify({backup,passphrase,confirmation})});alert(`Restauration terminée : ${result.users} compte(s), ${result.conversations} conversation(s). Vous allez être déconnecté.`);await logout();}catch(e){alert(`Restauration impossible : ${e.message}`);}finally{$('#importFile').value='';}}

$('#composer').addEventListener('submit',e=>{e.preventDefault();const v=$('#prompt').value;$('#prompt').value='';$('#prompt').style.height='auto';send(v)});
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit();}});
$('#prompt').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px';});
$('#newChat').onclick=newThread;$('#stop').onclick=()=>state.controller?.abort();$('#retryConnection').onclick=refresh;
let searchTimer;$('#conversationSearch').addEventListener('input',e=>{clearTimeout(searchTimer);const query=e.target.value.trim();if(query.length<2){state.searchIds=null;renderThreads();return;}searchTimer=setTimeout(async()=>{try{const {results}=await request(`/api/search?q=${encodeURIComponent(query)}`);state.searchIds=new Set(results.map(item=>item.id));renderThreads();}catch{state.searchIds=new Set();renderThreads();}},220);});
$('#projectsNav').onclick=()=>{$('#projectsPanel').hidden=!$('#projectsPanel').hidden;};
$('#addProject').onclick=async()=>{const name=prompt('Nom du nouveau projet');if(!name?.trim())return;try{const {project}=await request('/api/projects',{method:'POST',body:JSON.stringify({name:name.trim()})});state.projects.push(project);state.projectFilter=project.id;$('#projectsPanel').hidden=false;renderAll();}catch(error){alert(error.message);}};
$('#planningNav').onclick=()=>{$('#planningPanel').hidden=!$('#planningPanel').hidden;};
$('#taskForm').onsubmit=async event=>{event.preventDefault();const title=$('#taskTitle').value.trim(),dueDate=$('#taskDue').value||null;if(!title)return;const button=$('#taskForm button');button.disabled=true;try{const {task}=await request('/api/tasks',{method:'POST',body:JSON.stringify({title,dueDate,projectId:state.projectFilter})});state.tasks.unshift(task);$('#taskTitle').value='';$('#taskDue').value='';renderTasks();}catch(error){alert(error.message);}finally{button.disabled=false;}};
$('#pluginsNav').onclick=()=>{closeSidebar();openSettings('ai');};
$('#libraryNav').onclick=()=>{closeSidebar();openSettings('data');};
function openOnboarding(){$('#onboarding').showModal();}
const adminSetupKey=()=>`aster:admin-setup-v2:${state.auth?.user?.id||'local'}`;
async function finishAdminSetup(){const installationMode=document.querySelector('input[name="formula"]:checked')?.value||'solo';const button=$('#finishOnboarding');button.disabled=true;button.textContent='Enregistrement…';try{await request('/api/admin/config',{method:'POST',body:JSON.stringify({installationMode})});state.settings={...state.settings,installationMode};localStorage.setItem('aster:settings',JSON.stringify(state.settings));localStorage.setItem(adminSetupKey(),'done');$('#onboarding').close();openSettings('account');}catch(error){alert(error.message);}finally{button.disabled=false;button.textContent='Enregistrer et continuer';}}
$('#installGuideBtn').onclick=openOnboarding;$('#onboarding').addEventListener('cancel',e=>{if(!localStorage.getItem(adminSetupKey()))e.preventDefault();});$('#finishOnboarding').onclick=finishAdminSetup;$('#openProfileSetup').onclick=()=>{$('#onboarding').close();openSettings('profiles');};
$('#threads').onclick=async e=>{const b=e.target.closest('[data-id]');if(b){state.active=b.dataset.id;await hydrate(current());renderAll();closeSidebar();}};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));
$('#menuBtn').onclick=()=>{const open=!$('#sidebar').classList.contains('open');$('#sidebar').classList.toggle('open',open);$('#scrim').hidden=!open;$('#menuBtn').setAttribute('aria-expanded',String(open));};$('#scrim').onclick=closeSidebar;
const settingsTitles={account:'Compte',users:'Utilisateurs',profiles:'Profils',devices:'Appareils et sessions',security:'Sécurité',ai:'IA et capacités',network:'Réseau',data:'Données'};
async function loadAdminOverview(){if(state.auth?.user?.role!=='admin')return;try{const overview=await request('/api/admin/overview');state.admin=overview;$('#accountCount').textContent=overview.users.length;$('#accountLimit').textContent=overview.maxUsers;$('#createUserForm').hidden=overview.users.length>=overview.maxUsers;$('#adminUsers').innerHTML=overview.users.map(user=>`<article class="admin-user"><div><b>${escapeHtml(user.username)}</b><small>${user.role==='admin'?'Administrateur':'Utilisateur'} · ${user.profiles.length}/4 profils</small></div><div class="admin-profiles">${user.profiles.map(profile=>`<span>${escapeHtml(profile.name)}</span>`).join('')}</div>${user.profiles.length<4?`<button type="button" data-add-profile="${user.id}">＋ Profil</button>`:''}</article>`).join('');document.querySelectorAll('[data-add-profile]').forEach(button=>button.onclick=()=>addAdminProfile(button.dataset.addProfile));}catch(error){$('#adminUserState').textContent=error.message;}}
loadAdminOverview=async function(){if(state.auth?.user?.role!=='admin')return;try{const overview=await request('/api/admin/overview');state.admin=overview;$('#accountCount').textContent=overview.users.length;$('#accountLimit').textContent=overview.maxUsers;$('#createUserForm').hidden=overview.users.length>=overview.maxUsers;$('#adminUsers').innerHTML=overview.users.map(user=>`<article class="admin-user ${user.suspended?'suspended':''}"><div><b>${escapeHtml(user.username)}</b><small>${user.role==='admin'?'Administrateur':user.suspended?'Utilisateur suspendu':'Utilisateur'} · ${user.profiles.length}/4 profils</small></div><div class="admin-actions">${user.profiles.length<4?`<button type="button" data-add-profile="${user.id}">＋ Profil</button>`:''}${user.role!=='admin'?`<button type="button" data-toggle-user="${user.id}" data-suspended="${user.suspended}">${user.suspended?'Réactiver':'Suspendre'}</button><button type="button" class="danger" data-delete-user="${user.id}" data-username="${escapeHtml(user.username)}">Supprimer</button>`:''}</div><div class="admin-profiles">${user.profiles.map(profile=>`<span>${escapeHtml(profile.name)}${user.profiles.length>1?`<button type="button" aria-label="Supprimer ${escapeHtml(profile.name)}" data-delete-profile="${profile.id}" data-user="${user.id}" data-name="${escapeHtml(profile.name)}">×</button>`:''}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('[data-add-profile]').forEach(button=>button.onclick=()=>addAdminProfile(button.dataset.addProfile));document.querySelectorAll('[data-toggle-user]').forEach(button=>button.onclick=()=>toggleAdminUser(button.dataset.toggleUser,button.dataset.suspended!=='true'));document.querySelectorAll('[data-delete-user]').forEach(button=>button.onclick=()=>deleteAdminUser(button.dataset.deleteUser,button.dataset.username));document.querySelectorAll('[data-delete-profile]').forEach(button=>button.onclick=()=>deleteAdminProfile(button.dataset.user,button.dataset.deleteProfile,button.dataset.name));}catch(error){$('#adminUserState').textContent=error.message;}};
async function addAdminProfile(userId){const name=prompt('Nom du nouveau profil');if(!name?.trim())return;try{await request(`/api/admin/users/${encodeURIComponent(userId)}/profiles`,{method:'POST',body:JSON.stringify({name:name.trim()})});await loadAdminOverview();if(userId===state.auth.user.id){const auth=await request('/api/auth/status');state.auth=auth;}}catch(error){$('#adminUserState').textContent=error.message;}}
async function toggleAdminUser(userId,suspended){if(!confirm(`${suspended?'Suspendre':'Réactiver'} ce compte ?`))return;try{await request(`/api/admin/users/${encodeURIComponent(userId)}`,{method:'PATCH',body:JSON.stringify({suspended})});await loadAdminOverview();}catch(error){$('#adminUserState').textContent=error.message;}}
async function deleteAdminUser(userId,username){const confirmation=prompt(`Suppression définitive du compte et de ses conversations. Saisissez « ${username} » pour confirmer.`);if(confirmation!==username)return;try{await request(`/api/admin/users/${encodeURIComponent(userId)}`,{method:'DELETE',body:JSON.stringify({username:confirmation})});await loadAdminOverview();}catch(error){$('#adminUserState').textContent=error.message;}}
async function deleteAdminProfile(userId,profileId,name){const confirmation=prompt(`Suppression définitive du profil et de ses conversations. Saisissez « ${name} » pour confirmer.`);if(confirmation!==name)return;try{await request(`/api/admin/users/${encodeURIComponent(userId)}/profiles/${encodeURIComponent(profileId)}`,{method:'DELETE',body:JSON.stringify({name:confirmation})});await loadAdminOverview();if(userId===state.auth.user.id)state.auth=await request('/api/auth/status');}catch(error){$('#adminUserState').textContent=error.message;}}
async function createAdminUser(){const username=$('#newUsername').value.trim(),password=$('#newUserPassword').value,profileName=$('#newUserProfile').value.trim();$('#adminUserState').textContent='';try{await request('/api/admin/users',{method:'POST',body:JSON.stringify({username,password,profileName})});$('#newUsername').value='';$('#newUserPassword').value='';$('#newUserProfile').value='';await loadAdminOverview();}catch(error){$('#adminUserState').textContent=error.message;}}
async function configureCurrentPin(){const profile=state.auth?.profile;if(!profile)return;const pin=prompt('Nouveau PIN de 4 à 8 chiffres. Laissez vide pour supprimer le PIN.');if(pin===null)return;try{const data=await request(`/api/admin/users/${encodeURIComponent(state.auth.user.id)}/profiles/${encodeURIComponent(profile.id)}/pin`,{method:'POST',body:JSON.stringify({pin})});state.auth.profile=data.profile;state.auth.profiles=state.auth.profiles.map(item=>item.id===data.profile.id?data.profile:item);$('#pinStatus').textContent=data.profile.pinRequired?'PIN actif. Il sera demandé à la prochaine ouverture.':'Aucun PIN configuré.';}catch(error){alert(error.message);}}
async function loadAdminPolicy(){if(state.auth?.user?.role!=='admin'||!state.auth.profile)return;try{const {policy}=await request('/api/admin/policy');state.settings={...state.settings,allowedModels:(policy.allowedModels||[]).join(','),allowedSkills:(policy.allowedSkills||[]).join(','),profileRules:policy.rules||'',parallelRequests:policy.parallelRequests||1};$('#profileRules').value=state.settings.profileRules;$('#parallelRequests').value=state.settings.parallelRequests;document.querySelectorAll('.model-toggle').forEach(input=>input.checked=policy.allowedModels.includes(input.value));document.querySelectorAll('.skill-toggle').forEach(input=>input.checked=policy.allowedSkills.includes(input.value));}catch(error){$('#settingsSaveState').textContent=error.message;}}
function activateSettingsTab(tab){document.querySelectorAll('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x.dataset.settingsTab===tab));document.querySelectorAll('[data-settings-panel]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===tab));$('#settingsTitle').textContent=settingsTitles[tab];document.querySelector('.account-scroll').scrollTop=0;if(tab==='users')loadAdminOverview();if(tab==='ai')loadAdminPolicy();}
function openSettings(tab='account'){for(const [id,key] of [['customModel','model'],['accountEmail','accountEmail'],['displayName','displayName'],['profileRole','profileRole'],['rulePreset','rulePreset'],['profileRules','profileRules'],['networkMode','networkMode'],['proxyUrl','proxyUrl']])$('#'+id).value=state.settings[key]||'';const models=(state.settings.allowedModels||'').split(','),skills=(state.settings.allowedSkills||'').split(',');document.querySelectorAll('.model-toggle').forEach(x=>x.checked=models.includes(x.value));document.querySelectorAll('.skill-toggle').forEach(x=>x.checked=skills.includes(x.value));document.querySelector(`input[name="capacity"][value="${state.settings.capacityPreset||'essential'}"]`).checked=true;$('#parallelRequests').value=state.settings.parallelRequests||1;$('#capacityOverride').checked=!!state.settings.capacityOverride;$('#compactMode').checked=state.settings.compact;$('#token').value=state.token;activateSettingsTab(tab);$('#settings').showModal();}
$('#settingsBtn').onclick=()=>openSettings('account');$('#profileBtn').onclick=()=>{document.querySelector('.app').hidden=true;$('#authGate').hidden=false;renderProfileGate(state.auth);};document.querySelectorAll('[data-settings-tab]').forEach(button=>button.onclick=()=>activateSettingsTab(button.dataset.settingsTab));
$('#createUserBtn').onclick=createAdminUser;
$('#configurePin').onclick=configureCurrentPin;
$('#saveSettings').onclick=async()=>{const allowedModelList=[...document.querySelectorAll('.model-toggle:checked')].map(x=>x.value),allowedSkillList=[...document.querySelectorAll('.skill-toggle:checked')].map(x=>x.value),allowedModels=allowedModelList.join(','),allowedSkills=allowedSkillList.join(',');state.settings={...state.settings,model:$('#customModel').value||'gemma4:12b',compact:$('#compactMode').checked,accountEmail:$('#accountEmail').value.trim(),displayName:$('#displayName').value.trim()||'Profil principal',profileRole:$('#profileRole').value,allowedModels,rulePreset:$('#rulePreset').value,profileRules:$('#profileRules').value.trim(),allowedSkills,capacityPreset:document.querySelector('input[name="capacity"]:checked')?.value||'essential',parallelRequests:Math.max(1,Math.min(8,Number($('#parallelRequests').value)||1)),capacityOverride:$('#capacityOverride').checked,networkMode:$('#networkMode').value,proxyUrl:$('#proxyUrl').value.trim()};try{if(state.auth?.user?.role==='admin'&&state.auth.profile)await request('/api/admin/policy',{method:'PUT',body:JSON.stringify({allowedModels:allowedModelList,allowedSkills:allowedSkillList,rules:state.settings.profileRules,parallelRequests:state.settings.parallelRequests})});localStorage.setItem('aster:settings',JSON.stringify(state.settings));state.token=$('#token').value;sessionStorage.setItem('aster:token',state.token);$('#settingsSaveState').textContent='Réglages enregistrés et appliqués par le service local.';renderAll();refresh();}catch(error){$('#settingsSaveState').textContent=error.message;}};
$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();});
function showAuthState(id){['authLoading','setupForm','loginForm','profileGate'].forEach(x=>$('#'+x).hidden=x!==id);}
function authError(form,message=''){form.querySelector('.auth-error').textContent=message;}
function renderProfileGate(auth){showAuthState('profileGate');const host=$('#profileChoices');host.innerHTML='';for(const profile of auth.profiles||[]){const button=document.createElement('button');button.type='button';button.className='profile-choice';button.innerHTML=`<span>${escapeHtml(profile.name?.trim().charAt(0).toUpperCase()||'P')}</span><small>${escapeHtml(profile.name)}${profile.pinRequired?' · PIN':''}</small>`;button.onclick=()=>selectProfile(profile);host.append(button);}}
async function selectProfile(profile){const pin=profile.pinRequired?prompt(`PIN du profil « ${profile.name} »`):'';if(profile.pinRequired&&pin===null)return;try{const data=await request('/api/auth/profile',{method:'POST',body:JSON.stringify({profileId:profile.id,pin})});state.auth={...state.auth,profile:data.profile};await enterApp();}catch(e){authError($('#profileGate'),e.message);}}
async function enterApp(){state.settings.displayName=state.auth.profile?.name||'Profil';state.settings.profileRole=state.auth.user?.role||'personal';$('#profileRole').disabled=true;$('#configurePin').hidden=state.auth.user?.role!=='admin';$('#pinStatus').textContent=state.auth.profile?.pinRequired?'PIN actif. Il sera demandé à la prochaine ouverture.':'Aucun PIN configuré.';$('#authGate').hidden=true;document.querySelector('.app').hidden=false;const admin=state.auth.user?.role==='admin';document.querySelectorAll('[data-settings-tab="users"],[data-settings-tab="ai"],[data-settings-tab="network"]').forEach(x=>x.hidden=!admin);await loadThreads();await refresh();if(admin)await loadAdminOverview();if(admin&&!state.auth.installationConfigured&&!localStorage.getItem(adminSetupKey()))setTimeout(openOnboarding,180);}
async function logout(){await request('/api/auth/logout',{method:'POST'}).catch(()=>{});state.auth=null;state.threads=[];document.querySelector('.app').hidden=true;$('#authGate').hidden=false;showAuthState('loginForm');}
async function boot(){showAuthState('authLoading');try{const auth=await request('/api/auth/status');state.auth=auth;if(!auth.configured)return showAuthState('setupForm');if(!auth.authenticated)return showAuthState('loginForm');if(!auth.profile)return renderProfileGate(auth);await enterApp();}catch(e){showAuthState('loginForm');authError($('#loginForm'),'Le service local Aster est indisponible. Relancez-le puis réessayez.');}}
$('#setupForm').onsubmit=async e=>{e.preventDefault();authError(e.currentTarget);try{state.auth=await request('/api/auth/setup',{method:'POST',body:JSON.stringify({username:$('#setupUsername').value.trim(),password:$('#setupPassword').value,profileName:$('#setupProfile').value.trim()})});renderProfileGate(state.auth);}catch(err){authError(e.currentTarget,err.message);}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();authError(e.currentTarget);try{state.auth=await request('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#loginUsername').value.trim(),password:$('#loginPassword').value})});renderProfileGate(state.auth);}catch(err){authError(e.currentTarget,'Identifiant ou mot de passe incorrect.');}};
$('#logoutGate').onclick=logout;
$('#logoutSettings').onclick=()=>{$('#settings').close();logout();};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
boot();
